#pragma once
#include <memory>
#include <vector>
#include <tuple>
#include <string>
#include <format>
#define NOMINMAX
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <dxgi.h>
#include <d3d11.h>
#include <wrl.h>
#include <cuda.h>
#include <cuda_runtime.h>
#include <cudaD3D11.h>
#include <nvsdk_ngx_helpers_vsr.h>
#include <filter2.h>
#include <logger2.h>
